{
 "title": "Erigon Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "quantile",
    "query": "0.0,0.25,0.5, 0.9, 0.97, 0.99, 1"
   },
   { "name": "instance", "label": "instance", "query": { "query": "go_goroutines" } },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Blocks execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync Stages progress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\"}",
     "legendFormat": "{{ stage }}: {{instance}}"
    }
   ]
  },
  {
   "title": "Sync Stages progress rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(sync{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "{{ stage }}:  {{instance}}"
    }
   ]
  },
  {
   "title": "Exec v3: txs/s ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(exec_txs_done{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "txs apply:  {{instance}}"
    }
   ]
  },
  {
   "title": "Block Execution speed ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chain_execution_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "execution: {{instance}}"
    }
   ]
  },
  {
   "title": "Exec v3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(exec_repeats{instance=~\"$instance\"}[$rate_interval])/rate(exec_txs_done{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "repeats: {{instance}}"
    },
    {
     "expr": "rate(exec_triggers{instance=~\"$instance\"}[$rate_interval])/rate(exec_txs_done{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "triggers: {{instance}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(db_commit_seconds_count{phase=\"total\",instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "commit: {{instance}}"
    }
   ]
  },
  {
   "title": "Commit speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "db_commit_seconds{phase=\"total\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "total: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"gc_wall_clock\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_wall_clock: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"write\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "write: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"sync\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "sync: {{instance}}"
    },
    {
     "expr": "db_gc_self_rtime_cpu{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_self_rtime_cpu: {{instance}}"
    },
    {
     "expr": "db_gc_work_rtime_cpu{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_work_rtime_cpu: {{instance}}"
    },
    {
     "expr": "db_gc_work_rtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_work_rtime: {{instance}}"
    },
    {
     "expr": "db_gc_self_rtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_self_rtime: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"gc_cpu_time\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_cpu_time: {{instance}}"
    },
    {
     "expr": "db_gc_self_xtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_self_xtime: {{instance}}"
    },
    {
     "expr": "db_gc_work_pnl_merge_time{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "work_pnl_merge_time: {{instance}}"
    },
    {
     "expr": "db_gc_slef_pnl_merge_time{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "self_pnl_merge_time: {{instance}}"
    },
    {
     "expr": "db_gc_work_xtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_work_xtime: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "db_size{instance=~\"$instance\"}",
     "legendFormat": "size: {{instance}}"
    },
    {
     "expr": "db_mi_last_pgno{instance=~\"$instance\"}",
     "legendFormat": "db_mi_last_pgno: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Pages Ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "rate(db_pgops{phase=\"newly\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "newly: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"cow\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "cow: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"clone\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "clone: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"split\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "split: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"merge\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "merge: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"spill\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "spill: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"wops\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "wops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"unspill\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "unspill: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"gcrloops\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "gcrloops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"gcwloops\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "gcwloops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"gcxpages\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "gcxpages: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"msync\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "msync: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"fsync\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "fsync: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"minicore\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "minicore: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"prefault\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "prefault: {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tx_limit{instance=~\"$instance\"}",
     "legendFormat": "limit: {{instance}}"
    },
    {
     "expr": "tx_dirty{instance=~\"$instance\"}",
     "legendFormat": "dirty: {{instance}}"
    }
   ]
  },
  {
   "title": "GC and State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "db_gc_leaf{instance=~\"$instance\"}",
     "legendFormat": "gc_leaf: {{instance}}"
    },
    {
     "expr": "db_gc_overflow{instance=~\"$instance\"}",
     "legendFormat": "gc_overflow: {{instance}}"
    },
    {
     "expr": "exec_steps_in_db{instance=~\"$instance\"}/100",
     "legendFormat": "exec_steps_in_db: {{instance}}"
    }
   ]
  },
  {
   "title": "getrusage: minflt - soft page faults (reclaims), majflt - hard faults",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "rate(process_minor_pagefaults_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "soft: {{instance}}"
    },
    {
     "expr": "rate(process_major_pagefaults_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "hard: {{instance}}"
    }
   ]
  },
  {
   "title": "Commit counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "db_gc{phase=\"work_rxpages\", instance=~\"$instance\"}",
     "legendFormat": "work_rxpages: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"self_rsteps\", instance=~\"$instance\"}",
     "legendFormat": "self_rsteps: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"wloop\", instance=~\"$instance\"}",
     "legendFormat": "wloop: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"coalescences\", instance=~\"$instance\"}",
     "legendFormat": "coalescences: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"wipes\", instance=~\"$instance\"}",
     "legendFormat": "wipes: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"flushes\", instance=~\"$instance\"}",
     "legendFormat": "flushes: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"kicks\", instance=~\"$instance\"}",
     "legendFormat": "kicks: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"work_rsteps\", instance=~\"$instance\"}",
     "legendFormat": "gc_work_rsteps: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"self_xpages\", instance=~\"$instance\"}",
     "legendFormat": "self_xpages: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"work_majflt\", instance=~\"$instance\"}",
     "legendFormat": "gc_work_majflt: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"self_majflt\", instance=~\"$instance\"}",
     "legendFormat": "gc_self_majflt: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"self_counter\", instance=~\"$instance\"}",
     "legendFormat": "gc_self_counter: {{instance}}"
    },
    {
     "expr": "db_gc{phase=\"work_counter\", instance=~\"$instance\"}",
     "legendFormat": "gc_work_counter: {{instance}}"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rusage Total (\"last value\" - \"first value\" on selected period)",
   "type": "stat",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "ru_inblock{instance=~\"$instance\"}",
     "legendFormat": "inblock: {{instance}}"
    },
    {
     "expr": "ru_outblock{instance=~\"$instance\"}",
     "legendFormat": "outblock: {{instance}}"
    },
    {
     "expr": "ru_minflt{instance=~\"$instance\"}",
     "legendFormat": "minflt: {{instance}}"
    },
    {
     "expr": "ru_majflt{instance=~\"$instance\"}",
     "legendFormat": "majflt: {{instance}}"
    },
    {
     "expr": "system_disk_readbytes{instance=~\"$instance\"}",
     "legendFormat": "system_disk_readbytes: {{instance}}"
    },
    {
     "expr": "system_disk_writebytes{instance=~\"$instance\"}",
     "legendFormat": "system_disk_writebytes: {{instance}}"
    },
    {
     "expr": "db_pgops_newly{instance=~\"$instance\"}",
     "legendFormat": "pgops_newly: {{instance}}"
    },
    {
     "expr": "db_pgops_cow{instance=~\"$instance\"}",
     "legendFormat": "pgops_cow: {{instance}}"
    },
    {
     "expr": "db_pgops_clone{instance=~\"$instance\"}",
     "legendFormat": "pgops_clone: {{instance}}"
    },
    {
     "expr": "db_pgops_split{instance=~\"$instance\"}",
     "legendFormat": "pgops_split: {{instance}}"
    },
    {
     "expr": "db_pgops_merge{instance=~\"$instance\"}",
     "legendFormat": "pgops_merge: {{instance}}"
    },
    {
     "expr": "db_pgops_spill{instance=~\"$instance\"}",
     "legendFormat": "pgops_spill: {{instance}}"
    },
    {
     "expr": "db_pgops_unspill{instance=~\"$instance\"}",
     "legendFormat": "pgops_unspill: {{instance}}"
    },
    {
     "expr": "db_pgops_wops{instance=~\"$instance\"}",
     "legendFormat": "pgops_wops: {{instance}}"
    }
   ]
  },
  {
   "title": "Read/Write syscall/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_io_write_syscalls_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "in: {{instance}}"
    },
    {
     "expr": "rate(process_io_read_syscalls_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "out: {{instance}}"
    }
   ]
  },
  {
   "title": "cgo calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(go_cgo_calls_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "cgo_calls_count: {{instance}}"
    }
   ]
  },
  {
   "title": "Disk bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
   "targets": [
    {
     "expr": "rate(process_io_storage_read_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "read: {{instance}}"
    },
    {
     "expr": "rate(process_io_storage_written_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "write: {{instance}}"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "goroutines: {{instance}}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "threads: {{instance}}"
    }
   ]
  },
  {
   "title": "go memstat",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "stack_sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "stack_inuse: {{ instance }}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "mspan_sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "mcache_sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap_alloc: {{ instance }}"
    }
   ]
  },
  {
   "title": "GC Stop the World per sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds{quantile=\"0.75\",instance=~\"$instance\"}[$rate_interval])"
    }
   ]
  },
  {
   "title": "mem: resident set size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident mem: {{instance}}"
    },
    {
     "expr": "mem_data{instance=~\"$instance\"}",
     "legendFormat": "data: {{instance}}"
    },
    {
     "expr": "mem_stack{instance=~\"$instance\"}",
     "legendFormat": "stack: {{instance}}"
    },
    {
     "expr": "mem_locked{instance=~\"$instance\"}",
     "legendFormat": "locked: {{instance}}"
    },
    {
     "expr": "mem_swap{instance=~\"$instance\"}",
     "legendFormat": "swap: {{instance}}"
    }
   ]
  },
  {
   "title": "Process Mem: allocate objects/sec, free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "memstats_mallocs_total: {{ instance }}"
    },
    {
     "expr": "rate(go_memstats_frees_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "memstats_frees_total: {{ instance }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_system_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "system: {{instance}}"
    },
    {
     "expr": "increase(process_cpu_seconds_user_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "iowait: {{instance}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Host VMem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmem_total{instance=~\"$instance\"}",
     "legendFormat": "total: {{instance}}"
    },
    {
     "expr": "vmem_available{instance=~\"$instance\"}",
     "legendFormat": "available: {{instance}}"
    },
    {
     "expr": "vmem_used{instance=~\"$instance\"}",
     "legendFormat": "used: {{instance}}"
    },
    {
     "expr": "vmem_buffers{instance=~\"$instance\"}",
     "legendFormat": "buffers: {{instance}}"
    },
    {
     "expr": "vmem_cached{instance=~\"$instance\"}",
     "legendFormat": "cached: {{instance}}"
    },
    {
     "expr": "vmem_writeback{instance=~\"$instance\"}",
     "legendFormat": "writeback: {{instance}}"
    },
    {
     "expr": "vmem_dirty{instance=~\"$instance\"}",
     "legendFormat": "dirty: {{instance}}"
    },
    {
     "expr": "vmem_shared{instance=~\"$instance\"}",
     "legendFormat": "shared: {{instance}}"
    },
    {
     "expr": "vmem_mapped{instance=~\"$instance\"}",
     "legendFormat": "mapped: {{instance}}"
    }
   ]
  },
  {
   "title": "TxPool v2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pool_process_remote_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "process_remote_txs: {{ instance }}"
    },
    {
     "expr": "pool_add_remote_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "add_remote_txs: {{ instance }}"
    },
    {
     "expr": "pool_new_block{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "new_block: {{ instance }}"
    },
    {
     "expr": "pool_write_to_db{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "write_to_db: {{ instance }}"
    },
    {
     "expr": "pool_propagate_to_new_peer{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "propagate_to_new_peer: {{ instance }}"
    },
    {
     "expr": "pool_propagate_new_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "propagate_new_txs: {{ instance }}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(pool_process_remote_txs_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_process_remote_txs_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_add_remote_txs_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_add_remote_txs_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_new_block_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_new_block_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_write_to_db_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_write_to_db_count: {{ instance }}"
    }
   ]
  },
  {
   "title": "Cache hit-rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(delta(cache_total{result=\"hit\",name=\"txpool\",instance=~\"$instance\"}[1m]))/sum(delta(cache_total{name=\"txpool\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "hit rate: {{ instance }} "
    }
   ]
  },
  {
   "title": "Cache rps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 91 },
   "targets": [
    {
     "expr": "rate(cache_total{name=\"txpool\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ result }}: {{ instance }} "
    },
    {
     "expr": "rate(cache_timeout_total{name=\"txpool\",instance=~\"$instance\"}[1m])",
     "legendFormat": "timeout: {{ instance }} "
    }
   ]
  },
  {
   "title": "Cache keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cache_keys_total{name=\"txpool\",instance=~\"$instance\"}",
     "legendFormat": "keys: {{ instance }} "
    },
    {
     "expr": "cache_list_total{name=\"txpool\",instance=~\"$instance\"}",
     "legendFormat": "list: {{ instance }} "
    }
   ]
  },
  {
   "title": "DB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pool_write_to_db_bytes{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_write_to_db_bytes: {{ instance }}"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"success\"}[1m])",
     "legendFormat": "success {{ method }} {{ instance }} "
    },
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"failure\"}[1m])",
     "legendFormat": "failure {{ method }} {{ instance }} "
    }
   ]
  },
  {
   "title": "DB begin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "db_begin_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "db_begin_seconds: {{ method }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rpc_duration_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": " {{ method }} {{ instance }} {{ success }}"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go/goroutines: {{instance}}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go/threads: {{instance}}"
    }
   ]
  },
  {
   "title": "Cache keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cache_keys_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "keys: {{ instance }} "
    },
    {
     "expr": "cache_list_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "list: {{ instance }} "
    },
    {
     "expr": "cache_code_keys_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "code_keys: {{ instance }} "
    },
    {
     "expr": "cache_code_list_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "code_list: {{ instance }} "
    }
   ]
  },
  {
   "title": "Cache hit-rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 120 },
   "targets": [
    {
     "expr": "sum(delta(cache_total{result=\"hit\",name=\"rpc\",instance=~\"$instance\"}[1m]))/sum(delta(cache_total{name=\"rpc\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "hit rate: {{ instance }} "
    },
    {
     "expr": "sum(delta(cache_code_total{result=\"hit\",name=\"rpc\",instance=~\"$instance\"}[1m]))/sum(delta(cache_code_total{name=\"rpc\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "code hit rate: {{ instance }} "
    }
   ]
  },
  {
   "title": "Hidden",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Merkle Root calculation (stage 5)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "trie_subtrieloader_flatdb{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "trie_subtrieloader_flatdb: {{quantile}}, {{instance}}"
    },
    {
     "expr": "trie_subtrieloader_witnessdb{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "trie_subtrieloader_witnessdb: {{quantile}}, {{instance}}"
    }
   ]
  },
  {
   "title": "AutoDupsort Call/Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_op_set_count{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "rate(db_op_set_range_count{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "rate(db_op_get_count{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "rate(db_op_get_both{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "rate(db_op_get_both_range_count{instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "db_op_put{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_put_current{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "db.Get() latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 127 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "db_get{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "get: {{quantile}}, {{instance}}"
    }
   ]
  },
  {
   "title": "AutoDupsort Call/Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "db_op_set{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_set_range{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_get{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_get_both{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_get_both_range{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_put{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_put_current{quantile=\"$quantile\",instance=~\"$instance\"}"
    },
    {
     "expr": "db_op_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "AutoDupsort Put latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 132 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "mdbx_put_direct{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_direct: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_direct{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_direct: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_both_range{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_both_range: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_both_range{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_both_range: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_seek_exact{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_seek_exact: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_seek_exact{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_seek_exact: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_no_overwrite: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_no_overwrite{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_no_overwrite: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_upsert{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_upsert: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_upsert{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_upsert: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_current2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_current2: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_current2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_current2: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_upsert2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_upsert2: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_put_upsert2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_upsert2: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_del_current{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_put_current: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_del_current{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_del_current: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_seek_exact2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_seek_exact2: {{quantile}}, {{instance}}"
    },
    {
     "expr": "mdbx_seek_exact2{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "mdbx_seek_exact2: {{quantile}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "ingress: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
     "legendFormat": "dials: {{instance}}"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
     "legendFormat": "serves: {{instance}}"
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\",stage=\"headers\"}",
     "legendFormat": "Header: {{instance}}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync{stage=\"headers\", instance=~\"$instance\"}",
     "legendFormat": "blocks:{{instance}}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chain_head_header{instance=~\"$instance\"}",
     "legendFormat": "header: {{instance}}"
    },
    {
     "expr": "chain_head_receipt{instance=~\"$instance\"}",
     "legendFormat": "receipt: {{instance}}"
    },
    {
     "expr": "chain_head_block{instance=~\"$instance\"}",
     "legendFormat": "block: {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "executable: {{instance}}"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "gapped: {{instance}}"
    },
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "local: {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=~\"$instance\"}[1m])",
     "legendFormat": "valid: {{instance}}"
    },
    {
     "expr": "rate(txpool_invalid{instance=~\"$instance\"}[1m])",
     "legendFormat": "invalid: {{instance}}"
    },
    {
     "expr": "rate(txpool_underpriced{instance=\"$instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  {
   "title": "Private api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 },
   "targets": [
    {}
   ]
  },
  {
   "title": "gRPC call, error rates ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_started_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Calls: {{grpc_service}}.{{grpc_method}}, {{instance}}"
    },
    {
     "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_handled_total{instance=~\"$instance\",grpc_code!=\"OK\"}[1m])) ",
     "legendFormat": "Errors: {{grpc_service}}.{{grpc_method}}, {{instance}}"
    }
   ]
  }
 ]
}