{
 "title": "LUKSO Validator",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Total Validator Balance (Lyx)",
   "type": "stat",
   "description": "Sum of all validator balances.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"})",
     "legendFormat": "vbal"
    }
   ]
  },
  {
   "title": "Total Earnings (LYX)",
   "type": "stat",
   "description": "Total LYX return on the initial effective stake of active local validators.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"})-(count(validator_balance{job=\"validator\"} > 16 and validator_statuses{job=\"validator\"} == 3)*220)"
    }
   ]
  },
  {
   "title": "Total Return",
   "type": "stat",
   "description": "Total percentage return on the initial effective stake of active local validators. Excess deposits will be reflected as earnings.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance{job=\"validator\"}) - (count(validator_balance{job=\"validator\"} > 16 and validator_statuses{job=\"validator\"} == 3)*220))/(count(validator_balance{job=\"validator\"} > 16 and validator_statuses{job=\"validator\"} == 3)*220)  "
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "description": "Number of beacon nodes to which this node is connected.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"beacon node\"}"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "stat",
   "description": "The percentage of LYX balances expected to attest that are actually attesting.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"beacon node\"} / beacon_prev_epoch_active_gwei{job=\"beacon node\"} )"
    }
   ]
  },
  {
   "title": "Network Liveness",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((floor(beacon_clock_time_slot{job=\"beacon node\"}/32) - beacon_finalized_epoch{job=\"beacon node\"} - 2)/100))),0)"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "The percentage of LYX balances expected to attest that are actually attesting.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Participation Rate" }
   ],
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"beacon node\"} / beacon_prev_epoch_active_gwei{job=\"beacon node\"} )",
     "legendFormat": "participation rate"
    }
   ]
  },
  {
   "title": "Total Validator Balance (USD)",
   "type": "stat",
   "description": "Sum of all validator balances multiplied by the price of LYX in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lyxusd ", "legendFormat": "lyxusd" },
    {
     "expr": "sum(validator_balance{job=\"validator\"})",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Total Earnings (USD)",
   "type": "stat",
   "description": "Total earnings in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"})-(count(validator_balance{job=\"validator\"} > 16 and validator_statuses{job=\"validator\"} == 3)*220)",
     "legendFormat": "total_balance"
    },
    { "expr": "lyxusd", "legendFormat": "lyxusd" }
   ]
  },
  {
   "title": "LYX Price (USD)",
   "type": "stat",
   "description": "Price of Lyx in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lyxusd", "legendFormat": "lyxusd" }
   ]
  },
  {
   "title": "Max. Inactivity Score",
   "type": "stat",
   "description": "Current maximum inactvity score across all validators.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(validator_inactivity_score)"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Current, justified, and finalized epochs. In this order, these three values should be sequentially decreasing.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(beacon_clock_time_slot{job=\"beacon node\"} / 32)",
     "legendFormat": "current"
    },
    {
     "expr": "beacon_current_justified_epoch{job=\"beacon node\"}",
     "legendFormat": "justified"
    },
    {
     "expr": "beacon_finalized_epoch {job=\"beacon node\"} ",
     "legendFormat": "finalized"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_slot{job=\"beacon node\"}",
     "legendFormat": "current slot"
    },
    {
     "expr": "beacon_head_slot{job=\"beacon node\"}",
     "legendFormat": "head slot"
    }
   ]
  },
  {
   "title": "Local Validators",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Validators",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hourly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 1h != 0) - (220 * count(validator_balance{job=\"validator\"} > 16)) + (220 * count(validator_balance{job=\"validator\"} offset 1h > 16))"
    }
   ]
  },
  {
   "title": "Daily Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 1d != 0) - (220 * count(validator_balance{job=\"validator\"} > 16)) + (220 * count(validator_balance{job=\"validator\"} offset 1d > 16))"
    }
   ]
  },
  {
   "title": "Weekly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 7d != 0) - (220 * count(validator_balance{job=\"validator\"} > 16)) + (220 * count(validator_balance{job=\"validator\"} offset 7d > 16))"
    }
   ]
  },
  {
   "title": "Monthly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 30d != 0) - (220 * count(validator_balance{job=\"validator\"} > 16)) + (220 * count(validator_balance{job=\"validator\"} offset 30d > 16))"
    }
   ]
  },
  {
   "title": "Validator Counts",
   "type": "stat",
   "description": "Counts of active, slashed and exited validators.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Active\",job=\"beacon node\"} ",
     "legendFormat": "active"
    },
    {
     "expr": "validator_count{state=\"Slashed\",job=\"beacon node\"} ",
     "legendFormat": "slashed"
    },
    {
     "expr": "validator_count{state=\"Exited\",job=\"beacon node\"} ",
     "legendFormat": "exited"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "description": "Number of pending and existing validators over time. Pending validators are shown as positive values, while exiting validators are shown as negative values.",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "validators" }
   ],
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",job=\"beacon node\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",job=\"beacon node\"}",
     "legendFormat": "exiting"
    },
    {
     "expr": "validator_count{state=\"Slashing\",job=\"beacon node\"}",
     "legendFormat": "slashing"
    },
    {
     "expr": "validator_count{job=\"beacon node\", state=\"Active\"}",
     "legendFormat": "active validators"
    }
   ]
  },
  {
   "title": "Validator Queues",
   "type": "stat",
   "description": "Current number of pending and exiting validators",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",job=\"beacon node\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",job=\"beacon node\"}",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Hourly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 1h != 0) - (220 * count(validator_balance{job=\"validator\"} > 16)) +\t(220 * count(validator_balance{job=\"validator\"} offset 1h > 16)))/(220 * avg_over_time(count(validator_balance{job=\"validator\"} > 16)[1h:]))) * 365 * 24",
     "legendFormat": "annualized hourly return"
    }
   ]
  },
  {
   "title": "Daily Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 1d != 0) - (220 * count(validator_balance{job=\"validator\"} > 16)) +\t(220 * count(validator_balance{job=\"validator\"} offset 1d > 16)))/(220 * avg_over_time(count(validator_balance{job=\"validator\"} > 16)[1d:]))) * 365",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "Weekly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 7d != 0) - (220 * count(validator_balance{job=\"validator\"} > 16)) +\t(220 * count(validator_balance{job=\"validator\"} offset 7d > 16)))/(220 * avg_over_time(count(validator_balance{job=\"validator\"} > 16)[7d:]))) * (365/7)",
     "legendFormat": "annualized weekly return"
    }
   ]
  },
  {
   "title": "Monthly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"validator\"}) - sum(validator_balance{job=\"validator\"} offset 30d != 0) - (220 * count(validator_balance{job=\"validator\"} > 16)) +\t(220 * count(validator_balance{job=\"validator\"} offset 30d > 16)))/(220 * avg_over_time(count(validator_balance{job=\"validator\"} > 16)[30d:]))) * (365/30)",
     "legendFormat": "annualized monthly return"
    }
   ]
  },
  {
   "title": "Avg. Balance",
   "type": "stat",
   "description": "Average validator balance across the network",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\",job=\"beacon node\"} / validator_count{state=\"Active\",job=\"beacon node\"} / 1000000000",
     "legendFormat": "lyx"
    }
   ]
  },
  {
   "title": "Queue Lengths",
   "type": "stat",
   "description": "Estimated length of time until all pending and exiting validators have cleared the queues.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((validator_count{state=\"Pending\",job=\"beacon node\"}/4)*6.4)",
     "legendFormat": "pending"
    },
    {
     "expr": "((validator_count{state=\"Exiting\",job=\"beacon node\"}/4)*6.4)",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Validator Process Stats",
   "type": "table",
   "description": "validator stats by public key over the lifetime of the validator process ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(validator_statuses{job=\"validator\"}) by (pubkey)"
    },
    {
     "expr": "avg(validator_balance{job=\"validator\"}) by (pubkey)",
     "legendFormat": "balance"
    },
    {
     "expr": "avg(validator_successful_proposals{job=\"validator\"}) by (pubkey)"
    },
    {
     "expr": "avg(validator_successful_attestations{job=\"validator\"}) by (pubkey)"
    },
    {
     "expr": "avg(validator_successful_aggregations{job=\"validator\"}) by (pubkey)"
    },
    {
     "expr": "avg(validator_failed_attestations{job=\"validator\"}) by (pubkey)"
    },
    {
     "expr": "avg(validator_failed_aggregations{job=\"validator\"}) by (pubkey)"
    },
    {
     "expr": "avg(validator_inactivity_score{job=\"validator\"}) by (pubkey)"
    }
   ]
  },
  {
   "title": "Client Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers to which the beacon chain is connected",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"beacon node\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Process Uptimes",
   "type": "stat",
   "description": "The length of time the beacon chain and validator processes have been running.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"beacon node\"})/3600",
     "legendFormat": "beacon chain"
    },
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator\"})/3600",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Beacon Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{job=\"beacon node\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{job=\"beacon node\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Prysm Versions",
   "type": "table",
   "description": "Versions of the currently running Prysm clients.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "max(prysm_version) by (job, version)"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{job=\"validator\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{job=\"validator\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  }
 ]
}